#include <avr/io.h>

#ifndef PINS_H
#define PINS_H

// DEFINE POWER_SIGNAL
#define POWER_SIGNAL_DDR DDRC
#define POWER_SIGNAL_PORT PORTC
#define POWER_SIGNAL_PINS PINC
#define POWER_SIGNAL_PIN PC4
#define POWER_SIGNAL_ADC ADC4

// DEFINE CHARGING_SIGNAL
#define CHARGING_SIGNAL_DDR DDRC
#define CHARGING_SIGNAL_PORT PORTC
#define CHARGING_SIGNAL_PINS PINC
#define CHARGING_SIGNAL_ADC ADC5

// DEFINE POWER_LINE
#define POWER_LINE_DDR DDRD
#define POWER_LINE_PORT PORTD
#define POWER_LINE_PIN PD1

// DEFINE BATTERY_LINE_1
#define BATTERY_1_LINE_DDR DDRD
#define BATTERY_1_LINE_PORT PORTD
#define BATTERY_1_LINE_PIN PD0

// DEFINE BATTERY_LINE_2
#define BATTERY_2_LINE_DDR DDRD
#define BATTERY_2_LINE_PORT PORTD
#define BATTERY_2_LINE_PIN PD2

#endif
